#!/usr/bin/env node
// Builds Tests/GlanceCoreTests/Fixtures/letters.json: the readout letter for
// every row shape, computed by the design board's own rules. The functions
// below are copied verbatim from the signed-off board
// (plugins/quota-glance/web/design/menubar-readout/refined.html, letterForms
// and letterOf), with letterOf taking the window list as an argument. The
// Swift port (Sources/GlanceCore/ReadoutLetters.swift) is tested against the
// JSON, and scripts/tests/letters-fixture.test.mjs checks the JSON is this
// script's current output, so the fixture can be rebuilt without the board:
//
//   node scripts/letters-fixture.mjs        # rewrite the fixture
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const KIND = {session: 'S', weekly: 'W', weekly_fable: 'F', credits: 'C', monthly: 'M'};
const MODEL_KIND = {model_session: 'S', model_weekly: 'W'};
const TAKEN = new Set(Object.values(KIND));
const DIGITLIKE = new Set(['O', 'Q', 'I']);
function parseRow(r){
  if (r.startsWith('raw:')) { const rest = r.slice(4), c = rest.indexOf(':'); return {kind: 'raw', name: c >= 0 ? rest.slice(c + 1) : rest}; }
  const c = r.indexOf(':');
  return c >= 0 ? {kind: r.slice(0, c), name: r.slice(c + 1)} : {kind: r, name: ''};
}
const lettersIn = name => [...name].filter(ch => /[A-Za-z]/.test(ch));
const small = (name, n) => lettersIn(name).map(ch => ch.toLowerCase()).filter(ch => ch !== 'l').slice(0, n).join('');
const initials = (name, n) => { const s = lettersIn(name); return s[0].toUpperCase() + s.slice(1, n).join('').toLowerCase(); };
// [short, long]: long is used only when another row of the same provider has the same short form.
function letterForms(w){
  const k = parseRow(w.r);
  if (KIND[k.kind]) return [KIND[k.kind], KIND[k.kind]];
  if (MODEL_KIND[k.kind]) return [MODEL_KIND[k.kind] + small(k.name, 1), MODEL_KIND[k.kind] + small(k.name, 2)];
  const one = initials(k.name, 1), forced = TAKEN.has(one) || DIGITLIKE.has(one);
  return forced ? [initials(k.name, 2), initials(k.name, 3)] : [one, initials(k.name, 2)];
}
function letterOf(w, WINDOWS){
  const [short, long] = letterForms(w);
  return WINDOWS.some(o => o !== w && o.p === w.p && letterForms(o)[0] === short) ? long : short;
}

// Each scenario is one summary's full row list, in the summary's order.
const rows = (p, ...rs) => rs.map(r => ({p, r}));
export const SCENARIOS = [
  {name: 'board', windows: [
    ...rows('claude', 'session', 'weekly', 'weekly_fable', 'model_weekly:sonnet'),
    ...rows('codex', 'session', 'weekly', 'model_session:spark', 'model_weekly:spark'),
    ...rows('xai', 'credits', 'raw:xai:product/BUILD'),
  ]},
  {name: 'golden summary', windows: [
    ...rows('claude', 'session', 'weekly', 'weekly_fable'),
    ...rows('codex', 'session', 'weekly'),
    ...rows('xai', 'credits'),
  ]},
  {name: 'shared model initial', windows: [
    ...rows('codex', 'session', 'weekly', 'model_session:spark', 'model_weekly:spark', 'model_weekly:sage'),
  ]},
  {name: 'skipped l and monthly', windows: [
    ...rows('claude', 'monthly', 'model_weekly:llama', 'model_session:Opus-4'),
  ]},
  {name: 'raw rows', windows: [
    ...rows('xai', 'credits', 'raw:xai:sandbox', 'raw:xai:Omega', 'raw:xai:quota-2', 'raw:xai:image-gen', 'raw:xai:Images', 'raw:xai:BUILD', 'raw:xai:bulk', 'raw:noprovider'),
  ]},
];

export function build(){
  return {
    note: 'Generated by scripts/letters-fixture.mjs from the design board\'s letter rules. Do not edit by hand.',
    scenarios: SCENARIOS.map(s => ({
      name: s.name,
      rows: s.windows.map(w => {
        const [short, long] = letterForms(w);
        return {providerID: w.p, rowID: w.r, short, long, letter: letterOf(w, s.windows)};
      }),
    })),
  };
}

export const FIXTURE = new URL('../Tests/GlanceCoreTests/Fixtures/letters.json', import.meta.url);

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(FIXTURE, JSON.stringify(build(), null, 2) + '\n');
  console.log('Wrote ' + fileURLToPath(FIXTURE));
}
